### ISSUE TITLE
Importance sampling not working

### ISSUE THREAD

**Issue by txusser** [txusser/simpet#1]
When trying to run a simulation with importance sampling, an error (z mismatch between the object and activity table?) is generated in file simset_s1.log (second run simulation post-sampling) at the start of the second simulation.

**Comment by fjlopezgon** [comment]
Looking at the phg.rec files generated (where some zMin and zMax values have too many decimals) and the lines 128 and 129 of /src/simset/simset_tools.py, it seems that the _str()_ function includes some random decimals when its input parameter is a calculation.
