### ISSUE TITLE
Installation failed at "Downloading resources", no permission to Synology server

### ISSUE THREAD

**Issue by prabathbr** [txusser/simpet#16]
Hi,

Thank you very much for this interesting project. I am trying to install the "main" branch with "setup.py" and I got permission denied error after "Downloading resources from OneDrive" section as below. I am wondering whether this resource is moved to somewhere else and should be updated accordingly.  

```
Downloading resources from Onedrive...

EXE: sshpass -p simpet_dummy sftp -P 49166 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null simpet_install@mibiolab.synology.me:SIMPET/simpet_resources/Data.zip
Warning: Permanently added '[mibiolab.synology.me]:49166' (ED25519) to the list of known hosts.
Permission denied, please try again.
Traceback (most recent call last):
  File "/home/simpet/simpet/setup.py", line 337, in <module>
    download_resources(dest_dir)
  File "/home/simpet/simpet/setup.py", line 235, in download_resources
    rsystem(icom)
  File "/home/simpet/simpet/setup.py", line 25, in rsystem
    raise TypeError(command)
TypeError: sshpass -p simpet_dummy sftp -P 49166 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null simpet_install@mibiolab.synology.me:SIMPET/simpet_resources/Data.zip

```

**Comment by txusser** [comment]
Hi @prabathbr . We are making some important changes, including some improvements like dockerized installation. We are also changing the methods to download these files. I think  @YerePhy may be able to provide additional details.

In the meantime, you can obtain the necessary files from the following link https://gofile.me/5v8xA/UqpclNPOn

This is a temporary, suboptimal solution, but I will try to come with a fix in the comming days

**Comment by prabathbr** [comment]
> Hi @prabathbr . We are making some important changes, including some improvements like dockerized installation. We are also changing the methods to download these files. I think @YerePhy may be able to provide additional details.
> 
> In the meantime, you can obtain the necessary files from the following link https://gofile.me/5v8xA/UqpclNPOn
> 
> This is a temporary, suboptimal solution, but I will try to come with a fix in the comming days. Sometimes It takes me some time to answer GH, if you need further assistant do not hesitate to contact me by e-mail ([jsilva-ibis@us.es](mailto:jsilva-ibis@us.es))

Thank you very much. I have found the files in the "develop" branch under "assets" folder. I think I had to copy fruitcake contents to `/usr/bin` as well. Anyway, I was able to use them with following readme instructions and 'initialParams.yml' and generate sinograms and reconstructed images.

```
Create a simulation object. Sample Data is provided in Data/test: test_simu = simpet.SimPET('Data/test_image/testParams.yml')
```
I am wondering whether `simulation_time: 30     # secods` parameter corresponds to 30 seconds scan after injection a dose defined with `total_dose: 1            # mCi` parameter.

I also tried to use  "develop" branch as per readme, but I don't find mentioned `test.py` with sample python code to use that branch. Is there any place where I can find it ?

Thanks again for this wonderful framework.

**Comment by txusser** [comment]
Hi again @prabathbr,

I approved your pull request (August...). You do not need to copy fruitcake contents to **/usr/bin**, but you need to add

_export PATH=$SIMPET_PATH/fruitcake/bin:$PATH
export LD_LIBRARY_PATH=$SIMPET_PATH/fruitcake/book/lib:$LD_LIBRARY_PATH_

to your .bashrc . The setup.py should do this for you at some moment but maybe it did not because it crashed for you. About the rest of the parameters you are correct.

_simulation_time: 30_

This is the simulated acquisition time.

_total_dose: 1_

This is the total amount of radioactivity in your phantom. 

Note that if your phantom is larger that the FOV of the scanner, the activity in the FOV may be smaller). This is the activity in the whole phantom. 

I think you have been able to do the simulation, and your PR solves the issue with the files for the moment, is this correct?

Best,

Jesús

**Comment by prabathbr** [comment]
> Hi again @prabathbr,
> 
> I approved your pull request (August...). You do not need to copy fruitcake contents to **/usr/bin**, but you need to add
> 
> _export PATH=$SIMPET_PATH/fruitcake/bin:$PATH export LD_LIBRARY_PATH=$SIMPET_PATH/fruitcake/book/lib:$LD_LIBRARY_PATH_
> 
> to your .bashrc . The setup.py should do this for you at some moment but maybe it did not because it crashed for you. 

Thank you very much. Thant could be the reason for fruitcake issue. I will check again. :)

> I think you have been able to do the simulation, and your PR solves the issue with the files for the moment, is this correct?

Yes it is correct. I was able to do the simulation using attenuation and activity maps provided in "DATA" for brain FDG for Siemens mCT and Discovery ST scanners as a test.

Thanks again for the support.

**Comment by prabathbr** [comment]
> Hi @prabathbr,
> 
> Following the steps in `develop` branch and use `scripts/experiment.py` instead of `test.py` should allow you to do the simulations as well, the paths mantioned by @txusser are automatically added with this approach. In addition, you can override options and configuration groups using [hydra](https://hydra.cc/docs/intro/) syntax.
> 
> I hope your doubts have been resolved. Let me know if you got any question.

Thank you very much for the advice. I have followed above procedure and now it is working. I was able to generate images for GE Discovery ST and currently running on Siemens mMR.

I have noticed an issue only when "randoms" are enabled (when `add_randoms: 1 ` in yaml config).
I am getting segmentation fault for Siemens scanners both in main and develop branches as shown in below log, (GE Discovery ST works fine as I remember). 

Is there any special system requirement for Siemens scanners ? I have allocated 4 cores and 32 GB RAM for VM running Ubuntu 22.04.01. I can open a separate issue for if it helps with the troubleshooting. :)

```
(spdev) simpet@simpet-vm:~/simpet-devel/simpet/scripts$ python experiment.py
/home/simpet/miniconda3/envs/spdev/lib/python3.9/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config_test': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
Starting simulation for division_0
WARNING: add_randoms=1, so simulation is forced to realistic noise
Importance sampling is also being deactivated
All these means the simulation can take very long...
Starting simulation for division_1
WARNING: add_randoms=1, so simulation is forced to realistic noise
Importance sampling is also being deactivated
All these means the simulation can take very long...
Segmentation fault (core dumped)
Process Process-2:
Segmentation fault (core dumped)
Process Process-1:
```

**Comment by YerePhy** [comment]
Hi @prabathbr,

It seems that the program is trying to access a memory that it has no permission for. I've never faced this error before, we could start troubleshooting by increasing the available RAM for the VM or playing arround with `ulimit` and its options.

However, we have not tested Simpet in VM thoroughly, my recommendation is to use a partition or a separate machine with Ubuntu installed. That is our common setup.

**Comment by txusser** [comment]
I opened a new issue with this 

https://github.com/txusser/simpet/issues/22
