### ISSUE TITLE
Do I need to pre-install STIR and simSET if I want to use simPET

### ISSUE THREAD

**Issue by mele-y** [txusser/simpet#3]

**Comment by txusser** [comment]
Hi @mele-y,


Sorry for the the late reply. You don't need to pre-install STIR and SimSET. In fact you should not. The program used custom tweeked versions of both. You only need to run the setup.py script and it will install SimSET and STIR for you. Please let me know if you have problems with the configuration.

**Comment by mele-y** [comment]
Thanks very much! I have been able to successfully use this project to complete the simulation,by the way,what is output sinogram of this function?Is it attenaution factor or attenuation correction factor(ACF) or log(ACF) or something else?
https://github.com/txusser/simpet/blob/da57a33f83687fb5b53eb89dac33e208b4852b6c/src/simset/simset_tools.py#L489-L516
Thank again for your help.

**Comment by txusser** [comment]
This functions calls to SimSET "calcattenuation" executable. 

The output of this function is an attenuation sinogram (att.hdr). The values are attenuation coefficients (basically a projection of your att index map). You could multiply this by your simulation sinograms to produce an analytical correction.

I would love to know more about your project. You can contact me by e-mail (jesus@qubiotech) if you want some extra help.

**Comment by mele-y** [comment]
I'm trying to apply deep learning methods on PET scatter correction and image reconstruction,this project is a great tool to perform MC simulation easily to get train dataset.Thanks for your help.

**Comment by mele-y** [comment]
Sorry to bother you again.Is the activity map used for simulation  the ground turth distribution compared to the reconstruted image
